### ISSUE TITLE
isnt this detectable/ bannable?

### ISSUE THREAD

**Issue by TwoPointInfinity** [edoderg/edoStereo#5]
awhile back i used some kind of 3rd party program for stereo mod for discord and i got a warning about it and said if i kept it up  i could be banned. how long have you been using this? how safe do you feel about this?

**Comment by edoderg** [comment]
hello,

in general betterdiscord is against the tos, although discord doesn't care about users modifying their client, except ur using some risky plugins that can trigger the autoban system. you should be good using my plugin which only "converts" mono to stereo sound.
