### ISSUE TITLE
Specific person couldnt hear me with plugin enabled

### ISSUE THREAD

**Issue by DasMonschta** [edoderg/edoStereo#6]
One person in voice chat couldnt hear me.
I turned the plugin off and the person could hear me again.
Everyone else could hear me without a problem.

**Comment by DasMonschta** [comment]
so mobile and browser users cant hear me at all?
its not convertet to mono for them?

**Comment by DasMonschta** [comment]
but thats not what i wrote an issue for. 
the person couldnt hear me at all. no stereo no mono no nothing ^^

**Comment by edoderg** [comment]
oh my bad lolz. yeah they can't hear you when theyre on browser. mobile should work fine.

**Comment by DasMonschta** [comment]
so i can manually change bitrate in code and it should work? ill test it with that person as soon as i can

**Comment by edoderg** [comment]
try that out. if the problem still remains, it will more likely be something wrong with the end user.

**Comment by DasMonschta** [comment]
i went down from 512000 bits to 256000 bits. now that specific person could hear me.

**Comment by edoderg** [comment]
nice :D enjoy

**Comment by itsTyrion** [comment]
if you just use stereo (2.0), just drop it to 96-128k, unless you stream music and the other person has great headphones and ears. YT uses 128kbps VBR of the same codec (opus) btw (just in VariableBitRate, it can go between ~96-170k)
